### PR TITLE
ActiveDataProvider::prepareQuery() method

### PR DESCRIPTION
**Pull request by GHopperMSK**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  |

### CODE REVIEW

**Comment by GHopperMSK** [comment]
We have to change `UnqueryableQueryMock.php` file
```
class UnqueryableQueryMock extends Query
{
    /**
     * {@inheritdoc}
     */
    public function one($db = null)
    {
        if (!$this->emulateExecution) {
            throw new InvalidCallException();
        }
        return true;
    }
    /**
     * {@inheritdoc}
     */
    public function all($db = null)
    {
        if (!$this->emulateExecution) {
            throw new InvalidCallException();
        }
        return [];
    }
}
```
but it somewhere in another repo

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by rob006** [comment]
Are you sure that tests are working? IMO it is suspicious that tests passed without adjustments in `UnqueryableQueryMock`.

**Comment by rob006** [comment]
`ActiveQueryTest` is abstract...

**Comment by machour** [comment]
Test broken for db-mysql: https://travis-ci.com/yiisoft/db-mysql/jobs/172079026

```
1) yii\db\mysql\tests\ActiveDataProviderTest::testDoesNotPerformQueryWhenHasNoModels
An excessive models query was executed.
/home/travis/build/yiisoft/db-mysql/vendor/yiisoft/active-record/tests/unit/ActiveDataProviderTest.php:195
/home/travis/build/yiisoft/db-mysql/vendor/phpunit/phpunit/phpunit:61
```

**Comment by machour** [comment]
Original feature-request is at https://github.com/yiisoft/yii2/issues/15757

**Comment by GHopperMSK** [comment]
> Test broken for db-mysql: https://travis-ci.com/yiisoft/db-mysql/jobs/172079026

How did you run these tests? In my case, tests from only `ActiveDataFilterTest` file were run. As @rob006  noticed, there isn't `ActiveDataProviderTest` object to perform its tests (only abstract one).

**Comment by GHopperMSK** [comment]
If we even create `tests/unit/db/mysql/ActiveDataProviderTest.php` file
```
namespace yii\activerecord\tests\unit\db\mysql;

/**
 * @group db
 * @group mysql
 * @group data
 */
class ActiveDataProviderTest extends \yii\activerecord\tests\unit\ActiveDataProviderTest
{
    public $driverName = 'mysql';
}
```
we still get an error:
```
1) yii\activerecord\tests\unit\db\mysql\ActiveDataProviderTest::testActiveQuery
Something wrong when preparing database: No definition for "yii\db\ConnectionInterface" found
```
due to abstract `ActiveDataProviderTest::getConnection()` returns object of `\yii\db\Connection::class` not `yii\db\ConnectionInterface`, witch used in the repo everywhere!

**Pull request merged**
